In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [2]:
df = pd.read_csv('final_dataset.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3653 entries, 0 to 3652
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  3653 non-null   int64
 1   Date        3653 non-null   object
 2   DoW         3653 non-null   object
 3   Month       3653 non-null   int64
 4   Year        3653 non-null   int64
 5   btc_open    3643 non-null   float64
 6   btc_high    3643 non-null   float64
 7   btc_low     3643 non-null   float64
 8   btc_close   3643 non-null   float64
 9   oil_close   2637 non-null   float64
 10  oil_open    2637 non-null   float64
 11  oil_high    2637 non-null   float64
 12  oil_low     2637 non-null   float64
 13  gold_close  2564 non-null   object
 14  gold_open   2564 non-null   object
 15  gold_high   2564 non-null   object
 16  gold_low    2564 non-null   object
 17  dxy_close   2610 non-null   float64
 18  dxy_open    2610 non-null   float64
 19  dxy_high    2610 non-null   float64
 20  dxy_low     2610 non-null   float64
 21  IS_HOLIDAY  3653 non-null   float64
 22  IS_WEEKDAY  3653 non-null   int64
 23  Title       104 non-null    object
dtypes: float64(13), int64(4), object(7)
memory usage: 685.1+ KB

In [4]:
# Change dtype of columns
def clean_and_convert(column):
    if column.dtype == 'O':  # Checks if the column type is object (string data typically)
        return column.str.replace(',', '').astype(float)
    return column

In [5]:
df['gold_close'] = clean_and_convert(df['gold_close'])
df['gold_open'] = clean_and_convert(df['gold_open'])
df['gold_high'] = clean_and_convert(df['gold_high'])
df['gold_low'] = clean_and_convert(df['gold_low'])

# Change the datatype of 'Date' to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Change dtype 'IS_HOLIDAY' to int
df['IS_HOLIDAY'] = df['IS_HOLIDAY'].astype(int)

In [6]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Unnamed: 0,3653.0,1826.0,0.0,913.0,1826.0,2739.0,3652.0,1054.674594
Date,3653,2019-11-01 00:00:00,2014-11-01 00:00:00,2017-05-02 00:00:00,2019-11-01 00:00:00,2022-05-02 00:00:00,2024-10-31 00:00:00,NaN
Month,3653.0,6.52231,1.0,4.0,7.0,10.0,12.0,3.449345
Year,3653.0,2019.333425,2014.0,2017.0,2019.0,2022.0,2024.0,2.897193
btc_open,3643.0,18449.732976,176.9,1319.855,9314.13,29848.585,73079.38,20039.91454
btc_high,3643.0,18865.656794,211.73,1339.595,9466.35,30391.11,73750.07,20480.738577
btc_low,3643.0,18008.72678,171.51,1315.065,9149.39,29307.625,71334.09,19563.811246
btc_close,3643.0,18467.017137,178.1,1334.84,9316.63,29859.74,73083.5,20052.330675
oil_close,2637.0,61.8703,11.57,48.7,59.64,74.13,119.78,17.522667
oil_open,2637.0,61.894638,18.01,48.79,59.65,74.18,120.66,17.514253
oil_high,2637.0,62.903367,19.66,49.46,60.5,75.31,126.42,17.76924
oil_low,2637.0,60.817175,6.5,47.9,58.75,73.01,118.52,17.228812
gold_close,2564.0,1586.808892,1049.6,1258.075,1507.9,1862.55,2800.8,376.033521
gold_open,2564.0,1586.926775,1051.5,1258.175,1506.3,1863.725,2799.1,375.94326
gold_high,2564.0,1597.223518,1062.7,1264.975,1517.05,1874.525,2801.8,378.809995
gold_low,2564.0,1576.451307,1045.4,1251.875,1495.6,1848.35,2782.4,373.174651
dxy_close,2610.0,97.773188,86.98,94.21,97.095,101.395,114.11,4.923185
dxy_open,2610.0,97.762307,87.01,94.2125,97.08,101.4,114.18,4.922919
dxy_high,2610.0,98.071498,87.3,94.56,97.355,101.77,114.78,4.96316
dxy_low,2610.0,97.461854,86.88,93.905,96.785,101.0475,113.33,4.878896
IS_HOLIDAY,3653.0,0.02847,0.0,0.0,0.0,0.0,1.0,0.166333
IS_WEEKDAY,3653.0,0.714208,0.0,0.0,1.0,1.0,1.0,0.451853

In [7]:
df = df.sort_values(by='Date', ascending=True)

In [8]:
df.drop(columns=['Unnamed: 0'], axis=0)

,Date,DoW,Month,Year,btc_open,btc_high,btc_low,btc_close,oil_close,oil_open,...,gold_open,gold_high,gold_low,dxy_close,dxy_open,dxy_high,dxy_low,IS_HOLIDAY,IS_WEEKDAY,Title
3652,2014-11-01,Saturday,11,2014,338.65,340.53,321.05,325.75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
3651,2014-11-02,Sunday,11,2014,326.08,329.05,320.63,325.89,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
3650,2014-11-03,Monday,11,2014,325.57,334.00,325.48,327.55,78.78,80.59,...,1171.1,1173.4,1161.0,87.31,87.08,87.41,87.02,0,1,NaN
3649,2014-11-04,Tuesday,11,2014,327.16,331.77,325.08,330.49,77.19,78.22,...,1164.6,1175.0,1163.4,86.98,87.25,87.30,86.88,0,1,NaN
3648,2014-11-05,Wednesday,11,2014,330.68,343.37,330.68,339.49,78.68,77.36,...,1168.4,1169.3,1137.1,87.44,87.01,87.61,86.94,0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2024-10-27,Sunday,10,2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
3,2024-10-28,Monday,10,2024,NaN,NaN,NaN,NaN,67.38,68.98,...,2749.2,2758.3,2736.9,104.32,104.32,104.57,104.12,0,1,NaN
2,2024-10-29,Tuesday,10,2024,NaN,NaN,NaN,NaN,67.21,68.02,...,2741.9,2773.2,2741.9,104.32,104.31,104.64,104.21,0,1,NaN
1,2024-10-30,Wednesday,10,2024,NaN,NaN,NaN,NaN,68.61,67.47,...,2786.9,2801.8,2782.4,103.99,104.25,104.44,103.98,0,1,NaN
0,2024-10-31,Thursday,10,2024,NaN,NaN,NaN,NaN,69.26,69.10,...,2799.1,2801.2,2741.8,103.98,104.08,104.22,103.82,0,1,NaN

In [9]:
df['Date'].min()

Timestamp('2014-11-01 00:00:00')

In [10]:
df['Date'].max()

Timestamp('2024-10-31 00:00:00')

In [11]:
df = df.set_index('Unnamed: 0')

In [12]:
#drop rows with missing values in 'btc_open'
df = df.dropna(subset=['btc_open'])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3643 entries, 0 to 3642
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        3643 non-null   datetime64[ns]
 1   DoW         3643 non-null   object
 2   Month       3643 non-null   int64
 3   Year        3643 non-null   int64
 4   btc_open    3643 non-null   float64
 5   btc_high    3643 non-null   float64
 6   btc_low     3643 non-null   float64
 7   btc_close   3643 non-null   float64
 8   oil_close   2629 non-null   float64
 9   oil_open    2629 non-null   float64
 10  oil_high    2629 non-null   float64
 11  oil_low     2629 non-null   float64
 12  gold_close  2556 non-null   float64
 13  gold_open   2556 non-null   float64
 14  gold_high   2556 non-null   float64
 15  gold_low    2556 non-null   float64
 16  dxy_close   2602 non-null   float64
 17  dxy_open    2602 non-null   float64
 18  dxy_high    2602 non-null   float64
 19  dxy_low     2602 non-null   float64
 20  IS_HOLIDAY  3643 non-null   int64
 21  IS_WEEKDAY  3643 non-null   int64
 22  Title       104 non-null    object
dtypes: datetime64[ns](1), float64(16), int64(4), object(2)
memory usage: 683.1+ KB

In [14]:
# Imputing missing values in the oil, gold, and dollar data with interpolation
cols = ['oil_open', 'oil_high', 'oil_low', 'oil_close','gold_close', 'gold_open', 'gold_high', 
        'gold_low', 'dxy_close', 'dxy_open', 'dxy_high', 'dxy_low']
df[cols] = df[cols].interpolate(method='linear', axis=0)

In [15]:
# Change index to 'date'
df = df.set_index('Date')

In [16]:
## Running Averages for open and close data

# List of price columns
price_cols = ['btc_open', 'btc_close', 'oil_open', 'oil_close', 'gold_open', 'gold_close', 'dxy_open', 'dxy_close']

# Calculate running weekly and monthly averages
for col in price_cols:
    df[f'{col}_weekly_avg'] = df[col].rolling(window=7, min_periods=1).mean()
    df[f'{col}_monthly_avg'] = df[col].rolling(window=30, min_periods=1).mean()

In [17]:
# Asset categories and their respective price types
assets = {
    'btc': ['btc_open', 'btc_close', 'btc_high', 'btc_low'],
    'oil': ['oil_open', 'oil_close', 'oil_high', 'oil_low'],
    'gold': ['gold_open', 'gold_close', 'gold_high', 'gold_low'],
    'dxy': ['dxy_open', 'dxy_close', 'dxy_high', 'dxy_low']
}

# Calculate daily percentage changes
for asset, cols in assets.items():
    open_col, close_col, high_col, low_col = cols
    df[f'{asset}_Daily_percentage'] = ((df[close_col] - df[open_col]) / df[open_col] * 100)
    df[f'{asset}_Daily_max_percentage'] = ((df[high_col] - df[open_col]) / df[open_col] * 100)
    df[f'{asset}_Daily_min_percentage'] = ((df[low_col] - df[open_col]) / df[open_col] * 100)

In [18]:
# Calculate intraday volatility as the percentage difference between high and low prices
assets = ['btc', 'oil', 'gold', 'dxy']  # List of asset prefixes
for asset in assets:
    df[f'{asset}_intraday_volatility'] = ((df[f'{asset}_high'] - df[f'{asset}_low']) / df[f'{asset}_open']) * 100

In [19]:
# Calculate rolling volatility of daily percentage changes over 7-day and 30-day windows

for asset in assets:
    # Daily percentage change
    df[f'{asset}_daily_pct_change'] = df[f'{asset}_close'].pct_change() * 100
    
    # Rolling volatility (standard deviation of daily percentage changes)
    df[f'{asset}_rolling_volatility_7'] = df[f'{asset}_daily_pct_change'].rolling(window=7).std()
    df[f'{asset}_rolling_volatility_30'] = df[f'{asset}_daily_pct_change'].rolling(window=30).std()

In [20]:
df2= df

In [21]:
df

,DoW,Month,Year,btc_open,btc_high,btc_low,btc_close,oil_close,oil_open,oil_high,...,btc_rolling_volatility_30,oil_daily_pct_change,oil_rolling_volatility_7,oil_rolling_volatility_30,gold_daily_pct_change,gold_rolling_volatility_7,gold_rolling_volatility_30,dxy_daily_pct_change,dxy_rolling_volatility_7,dxy_rolling_volatility_30
Date,,,,,,,,,,,,,,,,,,,,,
2014-11-01,Saturday,11,2014,338.65,340.53,321.05,325.75,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-11-02,Sunday,11,2014,326.08,329.05,320.63,325.89,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-11-03,Monday,11,2014,325.57,334.00,325.48,327.55,78.78,80.59,80.980000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-11-04,Tuesday,11,2014,327.16,331.77,325.08,330.49,77.19,78.22,78.410000,...,NaN,-2.018279,NaN,NaN,-0.179518,NaN,NaN,-0.377964,NaN,NaN
2014-11-05,Wednesday,11,2014,330.68,343.37,330.68,339.49,78.68,77.36,79.350000,...,NaN,1.930302,NaN,NaN,-1.884046,NaN,NaN,0.528857,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-17,Thursday,10,2024,67617.08,67912.21,66647.39,67399.84,70.09,70.11,70.530000,...,1.925538,0.386709,1.567207,1.969992,0.601940,0.563343,0.568000,0.231683,0.144343,0.269125
2024-10-18,Friday,10,2024,67419.11,68969.75,67177.82,68418.79,68.69,70.17,70.670000,...,1.906438,-1.997432,1.581425,2.004287,0.831025,0.408514,0.580921,-0.327458,0.211646,0.271183
2024-10-19,Saturday,10,2024,68418.98,68668.01,68024.64,68362.73,69.14,69.76,70.576667,...,1.879617,0.655117,1.730497,1.977780,0.108669,0.376192,0.575219,0.167488,0.213397,0.271008
2024-10-20,Sunday,10,2024,68364.18,69359.01,68105.72,69001.70,69.59,69.35,70.483333,...,1.883197,0.650853,1.843030,1.981980,0.108551,0.336675,0.539713,0.167208,0.214989,0.271282
2024-10-21,Monday,10,2024,69009.37,69408.10,66873.84,67525.97,70.04,68.94,70.390000,...,1.935550,0.646645,1.925400,1.982504,0.108433,0.287005,0.539652,0.166929,0.216428,0.271179